### ISSUE TITLE
Traefik logs show only Cloudflare IPs

### ISSUE THREAD

**Issue by casudo** [BilikoX/cloudflarewarp#1]
I only see the Cloudflare IPs in my Traefik access.log. Traefik v2.10.5.

My traefik.yml:
```yaml
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
      middlewares:
        - my-cloudflarewarp@file
  websecure:
    address: :443
    http:
      middlewares:
        - my-cloudflarewarp@file

experimental:
  plugins:
    cloudflarewarp:
      moduleName: "github.com/Amadeus331/cloudflarewarp"
      version: "v1.3.4"
```

my config.yml:
```yaml
http:
  middlewares:
    my-cloudflarewarp:
      plugin:
        cloudflarewarp:
          disableDefault:  "true"
          trustip:
            -  2400:cb00::/32 
            -  2606:4700::/32 
            -  2803:f800::/32 
            -  2405:b500::/32 
            -  2405:8100::/32 
            -  2a06:98c0::/29 
            -  2c0f:f248::/32 
            -  173.245.48.0/20 
            -  103.21.244.0/22 
            -  103.22.200.0/22 
            -  103.31.4.0/22 
            -  141.101.64.0/18 
            -  108.162.192.0/18 
            -  190.93.240.0/20 
            -  188.114.96.0/20 
            -  197.234.240.0/22 
            -  198.41.128.0/17 
            -  162.158.0.0/15 
            -  104.16.0.0/13 
            -  104.24.0.0/14 
            -  172.64.0.0/13 
            -  131.0.72.0/22
```

**Comment by BilikoX** [comment]
If you see request_X_Real_Ip is the same as request_Cf_Connecting_Ip in access.log, then there is no problem

**Comment by BilikoX** [comment]
> I only see the Cloudflare IPs in my Traefik access.log. Traefik v2.10.5.
> 
> My traefik.yml:
> 
> ```yaml
> entryPoints:
>   web:
>     address: :80
>     http:
>       redirections:
>         entryPoint:
>           to: websecure
>           scheme: https
>       middlewares:
>         - my-cloudflarewarp@file
>   websecure:
>     address: :443
>     http:
>       middlewares:
>         - my-cloudflarewarp@file
> 
> experimental:
>   plugins:
>     cloudflarewarp:
>       moduleName: "github.com/Amadeus331/cloudflarewarp"
>       version: "v1.3.4"
> ```
> 
> my config.yml:
> 
> ```yaml
> http:
>   middlewares:
>     my-cloudflarewarp:
>       plugin:
>         cloudflarewarp:
>           disableDefault:  "true"
>           trustip:
>             -  2400:cb00::/32 
>             -  2606:4700::/32 
>             -  2803:f800::/32 
>             -  2405:b500::/32 
>             -  2405:8100::/32 
>             -  2a06:98c0::/29 
>             -  2c0f:f248::/32 
>             -  173.245.48.0/20 
>             -  103.21.244.0/22 
>             -  103.22.200.0/22 
>             -  103.31.4.0/22 
>             -  141.101.64.0/18 
>             -  108.162.192.0/18 
>             -  190.93.240.0/20 
>             -  188.114.96.0/20 
>             -  197.234.240.0/22 
>             -  198.41.128.0/17 
>             -  162.158.0.0/15 
>             -  104.16.0.0/13 
>             -  104.24.0.0/14 
>             -  172.64.0.0/13 
>             -  131.0.72.0/22
> ```

If you see request_X_Real_Ip is the same as request_Cf_Connecting_Ip in access.log, then there is no problem

**Comment by BilikoX** [comment]
The defaultMode for fields.headers is drop. 
see:
https://doc.traefik.io/traefik/observability/access-logs/#limiting-the-fieldsincluding-headers
```
# Limiting the Logs to Specific Fields
accessLog:
  filePath: "/path/to/access.log"
  format: json
  fields:
    defaultMode: keep
    names:
      ClientUsername: drop
    headers:
      defaultMode: keep
      names:
        User-Agent: redact
        Authorization: drop
        Content-Type: keep
```
